const test=require('node:test');const assert=require('node:assert/strict');const C=require('../core.js');const D=require('../data/beers.json');
const point=(id,price,score,style='a')=>({id,name:id,price,activeRating:{value:score},eligible:true,style});
test('normalize volume and pack; never infer null as free',()=>{assert.equal(C.cost({total:60,quantity:24,volumeMl:330},'unit'),2.5);assert.equal(C.cost({total:60,quantity:24,volumeMl:330},'order'),60);assert.ok(Math.abs(C.cost({total:60,quantity:24,volumeMl:330})-3.787878787878788)<1e-12);assert.equal(C.cost(null),null);assert.equal(C.cost({total:0,quantity:1,volumeMl:500}),null);});
test('exact Pareto: lower price AND >=score dominates; tradeoffs survive',()=>{const p=[point('a',5,3),point('b',10,4),point('c',12,3.8),point('d',4,2.5)];assert.deepEqual(C.frontier(p).map(x=>x.id),['d','a','b']);});
test('ties, equal price/equal score, duplicate points',()=>{const p=[point('a',10,4),point('b',10,4),point('c',10,3.9),point('d',12,4)];assert.deepEqual(C.frontier(p).map(x=>x.id),['a','b']);});
test('cross-style dominance disabled only in same-style mode',()=>{const p=[point('a',5,4,'lager'),point('b',10,3.8,'stout')];assert.equal(C.frontier(p).length,1);assert.equal(C.frontier(p,'style').length,2);});
test('empty and invalid rows excluded',()=>{assert.deepEqual(C.frontier([]),[]);assert.deepEqual(C.frontier([{...point('a',1,4),eligible:false}]),[]);assert.deepEqual(C.frontier([{...point('a',1,4),price:null}]),[]);});
test('v1.2 default: 67 visible, 21 eligible, seven per-platform frontier nodes',()=>{const a=C.analyze(D,C.defaults());assert.equal(a.rows.length,67);assert.equal(a.eligible.length,21);assert.deepEqual(a.edge.map(b=>b.id),['pang','benediktiner','franziskaner','salt','karmeliet','pseudosue','kingsue']);assert.equal(a.best,null);assert.equal(a.bestByCohort.length,3);assert.equal(a.eligible.some(b=>b.id==='weihen'),false);});
test('ambiguous prices require explicit opt-in; historical reference is visible by default',()=>{const s={...C.defaults(),includeHistoric:true,includeAmbiguous:true};const a=C.analyze(D,s);assert.ok(a.eligible.some(b=>b.id==='weihen'));assert.ok(a.eligible.some(b=>b.id==='kingsue'));assert.ok(a.eligible.some(b=>b.id==='franziskaner'));});
test('manual price overrides and replaces historical restrictions',()=>{const s=C.defaults();s.overrides.kingsue={total:35,quantity:1,volumeMl:473};const r=C.resolve(D.beers.find(b=>b.id==='kingsue'),s);assert.ok(r.eligible);assert.equal(r.activeQuote.personal,true);assert.equal(r.price,35/473*500);});
test('budget below minimum returns no recommendation, not automatic upsell',()=>{const s={...C.defaults(),budget:1};assert.equal(C.analyze(D,s).best,null);});
test('personal score mode never fills missing personal scores from BA',()=>{const s={...C.defaults(),scoreMode:'personal'};assert.equal(C.analyze(D,s).eligible.length,0);s.personalScores.snow=4.5;assert.equal(C.analyze(D,s).eligible.length,1);assert.equal(C.analyze(D,s).best.id,'snow');});
test('minimum sample and ABV filters: unknowns excluded under restrictive limit',()=>{const s={...C.defaults(),minRatings:1000,maxAbv:5};const a=C.analyze(D,s);assert.equal(a.eligible.some(b=>b.id==='benediktiner'),false);assert.equal(a.rows.some(b=>b.abv===null),false);});
test('identity placeholders never become comparable through manual input',()=>{const s={...C.defaults(),scoreMode:'personal'};s.overrides.nadu={total:1,quantity:1,volumeMl:500};s.personalScores.nadu=5;assert.equal(C.resolve({...D.beers.find(b=>b.id==='nadu'),identityPending:true},s).eligible,false);});
test('personal import rejects bad shapes/unknown ids/infinity and retains only allowed keys',()=>{const ids=new Set(D.beers.map(b=>b.id));const v=C.validateImport({schemaVersion:1,overrides:{paulaner:{total:40,quantity:6,volumeMl:500,script:'evil'}},shortlist:['paulaner','paulaner']},ids);assert.deepEqual(v.shortlist,['paulaner']);assert.equal(v.overrides.paulaner.script,undefined);assert.throws(()=>C.validateImport({schemaVersion:1,overrides:{evil:{total:1,quantity:1,volumeMl:1}}},ids));assert.throws(()=>C.validateImport({schemaVersion:1,personalScores:{paulaner:6}},ids));assert.throws(()=>C.validateImport({schemaVersion:1,overrides:{paulaner:{total:Infinity,quantity:1,volumeMl:500}}},ids));});
test('data integrity and traceable ratings/quotes/review sources',()=>{const seen=new Set();for(const b of D.beers){assert.ok(!seen.has(b.id));seen.add(b.id);if(b.rating){assert.ok(['BeerAdvocate','酒花儿','Untappd'].includes(b.rating.platform));assert.equal(b.rating.scale,5);assert.ok(Number.isInteger(b.rating.count)&&b.rating.count>0);assert.ok(D.sources[b.rating.sourceId]);}if(b.quote){assert.ok(C.validQuote(b.quote));assert.ok(D.sources[b.quote.sourceId]);}for(const sid of b.review.sourceIds)assert.ok(D.sources[sid]);}assert.equal(D.beers.length,67);});
test('quote entry threshold is not a fabricated market price',()=>{const b=point('unknown',null,4);const peers=[point('peer1',12,4.1),point('peer2',15,4.5),point('lower',3,3)];assert.deepEqual(C.entryLimit(b,peers),{price:12,strict:true,peerIds:['peer1']});assert.equal(C.entryLimit(point('equal',null,4.1),peers).strict,false);assert.equal(C.entryLimit(point('better',null,4.9),peers).price,null);});


test('scores from different platforms never dominate each other',()=>{const a={...point('a',1,5),activeRating:{value:5,platform:'BeerAdvocate'}},b={...point('b',20,3),activeRating:{value:3,platform:'酒花儿'}};assert.equal(C.dominates(a,b),false);assert.equal(C.frontier([a,b]).length,2);assert.equal(C.entryLimit(b,[a]).price,null);});
test('all 67 have chart entries; unknown coordinates stay null',()=>{const s=C.defaults(),rows=C.analyze(D,s).rows.map(b=>C.displayPoint(b,s));assert.equal(rows.length,67);assert.ok(rows.filter(b=>Number.isFinite(b.plotPrice)).length===42);assert.equal(rows.find(b=>b.id==='augerta').plotRating,null);assert.equal(rows.filter(b=>b.plotRating).length,41);});
test('editorial ceilings and related scores do not create evidence eligibility',()=>{const s=C.defaults();for(const id of ['vitus','asahi','heineken-keg','augerta']){const b=C.resolve(D.beers.find(x=>x.id===id),s);assert.equal(b.eligible,false);}const v=C.displayPoint(C.resolve(D.beers.find(x=>x.id==='vitus'),s),s);assert.equal(v.priceBasis,'editorial-ceiling');assert.equal(v.price,null);});
test('written comments are not a rating sample count',()=>{const s={...C.defaults(),minRatings:100};const a=C.analyze(D,s);assert.equal(a.eligible.some(b=>b.id==='salt'),false);assert.equal(a.eligible.some(b=>b.id==='pang'),true);assert.ok(C.resolve(D.beers.find(b=>b.id==='salt'),s).reasons.includes('评分人数未知（只有评论数）'));});
test('historical toggle excludes known expired prices from calculation, not visibility',()=>{const s={...C.defaults(),includeHistoric:false},a=C.analyze(D,s);assert.equal(a.rows.length,67);assert.equal(a.eligible.some(b=>b.id==='kingsue'),false);assert.equal(C.displayPoint(a.rows.find(b=>b.id==='kingsue'),s).reference,true);});
test('original research coverage stays intact while new user-only entries remain unverified',()=>{assert.equal(D.beers.filter(b=>b.rating).length,35);assert.equal(D.beers.filter(b=>b.quote).length,30);assert.equal(D.beers.filter(b=>b.relatedRating).length,6);assert.equal(Object.keys(D.sources).length,83);for(const b of D.beers.filter(b=>b.coverage.identity!=='user-list-unverified')){assert.ok(b.review.positive&&b.review.caution&&b.review.fit);assert.ok(b.review.sourceIds.length);assert.ok(b.purchaseGuide.ceiling>0&&b.purchaseGuide.volumeMl>0);assert.equal(b.purchaseGuide.type,'editorial-ceiling');assert.ok(b.coverage&&b.researchNote);if(b.relatedRating)assert.ok(D.sources[b.relatedRating.sourceId]);}});
test('platform filter and personal mode use independent correct scopes',()=>{const s={...C.defaults(),scorePlatform:'Untappd'};const a=C.analyze(D,s);assert.deepEqual(a.rows.map(b=>b.id),['pang']);assert.equal(a.best.id,'pang');const p=C.analyze(D,{...s,scoreMode:'personal'});assert.equal(p.rows.length,67);assert.equal(p.eligible.length,0);});
test('reference metadata never changes Pareto results',()=>{const s=C.defaults(),original=C.analyze(D,s).edge.map(b=>b.id),d=JSON.parse(JSON.stringify(D));for(const b of d.beers){if(b.purchaseGuide)b.purchaseGuide.ceiling=.01;if(b.relatedRating)b.relatedRating.value=5;}assert.deepEqual(C.analyze(d,s).edge.map(b=>b.id),original);});
